apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data
  labels:
    app: qbittorrent 

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/k8s/volumes/qbittorrent-data    
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
               - kube-worker-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
  namespace: qbittorrent
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: qbittorrent
