apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
  labels:
    app: qbittorrent 

spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/k8s/volumes/qbittorrent-config    
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
               - kube-worker-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  selector:
    matchLabels:
      app: qbittorrent
