apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n
spec:
  storageClassName: local
  accesModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/k8s/volumes/n8n-data
  nodeAffinity:
    required:
      nodesSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-2
