apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server

spec:
  capacity:
    storage: 8Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/k8s/volumes/prometheus-server
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In 
              values:
                - kube-worker-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/k8s/volumes/prometheus-alertmanager
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-2
