---
# Source: homarr/templates/homarr-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: homarr
  labels:
    helm.sh/chart: homarr-3.7.1
    app.kubernetes.io/name: homarr
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/version: "v1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 7575
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: homarr
    app.kubernetes.io/instance: homarr
