apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config
  labels:
    app: home-assistant
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/k8s/volumes/homeassistant_config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-2
