apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/expelliarmus625/trinity.git
    targetRevision: dev
    path: jellyfin

    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
