# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jellyfin-config
#   labels:
#     app: jellyfin
# spec:
#   capacity:
#     storage: 250Mi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local
#   local:
#     path: /mnt/k8s/volumes/jellyfin-config
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - kube-worker-2
#
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jellyfin-cache
#   labels:
#     app: jellyfin
# spec:
#   capacity:
#     storage: 500Mi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local
#   local:
#     path: /mnt/k8s/volumes/jellyfin-cache
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - kube-worker-2
#
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jellyfin-media
#   labels:
#     app: jellyfin
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local
#   local:
#     path: /mnt/k8s/volumes/jellyfin-media
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - kube-worker-2
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  # selector:
  #   matchLabels:
  #     app: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  # selector:
  #   matchLabels:
  #     app: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # selector:
  #   matchLabels:
  #     app: jellyfin
